{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "2beaaadb",
   "metadata": {},
   "outputs": [],
   "source": [
    "function copyUniqueLeads() {\n",
    "  const ss = SpreadsheetApp.getActiveSpreadsheet();\n",
    "  const masterSheet = ss.getSheetByName(\"MASTER DATABASE 2025 Template\");\n",
    "  const leadsSheet = ss.getSheetByName(\"Non-Repeated Leads for TS\");\n",
    "\n",
    "\n",
    "  if (leadsSheet.getLastRow() > 1) {\n",
    "      // Clear all except column AB (28)\n",
    "    leadsSheet.getRange(2, 1, leadsSheet.getLastRow() - 1, 27).clearContent();\n",
    "    const remainingCols = leadsSheet.getLastColumn() - 28;\n",
    "    if (remainingCols > 0) {\n",
    "      leadsSheet.getRange(2, 29, leadsSheet.getLastRow() - 1, remainingCols).clearContent();\n",
    "    }\n",
    "  }\n",
    "\n",
    "\n",
    "  // Column mapping [MASTER index → TARGET index]\n",
    "  const COLUMN_MAP = [\n",
    "    [0, 0],   // A → A\n",
    "    [1, 1],   // B → B\n",
    "    [2, 2],   // C → C (date)\n",
    "    [3, 3],   // D → D (Acra Registered Name)\n",
    "    [4, 4],   // E → E (FIXED)\n",
    "    [7, 5],   // H → F\n",
    "    [26, 6],  // AA → G (sub-industry)\n",
    "    [18, 7],  // S → H (biz type)\n",
    "    [23, 8],  // X → I (ownership type)\n",
    "    [27, 9],  // AB → J (biz model)\n",
    "    [40, 10], // AO → K\n",
    "    [41, 11], // AP → L\n",
    "    [42, 12], // AQ → M\n",
    "    [43, 13], // AR → N (Phone 1)\n",
    "    [44, 14], // AS → O\n",
    "    [45, 15], // AT → P\n",
    "    [46, 16], // AU → Q\n",
    "    [47, 17], // AV → R (PIC 2 Designation)\n",
    "    [48, 18], // AW → S (Phone 2)\n",
    "    [49, 19], // AX → T (PIC 3 Designation)\n",
    "    [50, 20], // AY → U\n",
    "    [51, 21], // AZ → V\n",
    "    [52, 22], // BA → W\n",
    "    [53, 23], // BB → X (Phone 3)\n",
    "    [54, 24], // BC → Y\n",
    "    [56, 25], // BE → Z\n",
    "    [57, 26], // BF → AA\n",
    "  ];\n",
    "\n",
    "\n",
    "  // Phone columns to check for duplicates [MASTER index, TARGET index]\n",
    "  const PHONE_COLS = [[43,13], [48,18], [53,23]]; // AR/N, AW/S, BB/X\n",
    "\n",
    "\n",
    "  const masterData = masterSheet.getDataRange().getValues();\n",
    "  const globalPhones = new Set();\n",
    "  const newRows = [];\n",
    "  const skippedLog = [];\n",
    "\n",
    "\n",
    "  const targetData = leadsSheet.getRange(1, 1, leadsSheet.getLastRow(), leadsSheet.getLastColumn()).getValues();\n",
    "  for (let i = 1; i < targetData.length; i++) {\n",
    "    PHONE_COLS.forEach(([_, targetIdx]) => {\n",
    "      const phone = targetData[i][targetIdx]?.toString().trim();\n",
    "      if (phone) globalPhones.add(phone);\n",
    "    });\n",
    "  }\n",
    "\n",
    "\n",
    "  // Process master data\n",
    "  for (let i = 1; i < masterData.length; i++) {\n",
    "    const masterRow = masterData[i];\n",
    "    const targetRow = Array(27).fill(''); // Adjust if target has more columns\n",
    "   \n",
    "    // Copy mapped columns\n",
    "    COLUMN_MAP.forEach(([masterIdx, targetIdx]) => {\n",
    "      targetRow[targetIdx] = masterRow[masterIdx] !== undefined ? masterRow[masterIdx] : '';\n",
    "    });\n",
    "\n",
    "\n",
    "    // Check unique phone num\n",
    "    let hasValidPhone = false;\n",
    "    const phoneStatus = [];\n",
    "   \n",
    "    PHONE_COLS.forEach(([masterIdx, targetIdx]) => {\n",
    "      const rawPhone = masterRow[masterIdx];\n",
    "      const phone = rawPhone ? rawPhone.toString().replace(/[\\s\\-]/g, '').trim() : '';\n",
    "     \n",
    "      if (phone) {\n",
    "        if (!globalPhones.has(phone)) {\n",
    "          globalPhones.add(phone);\n",
    "          hasValidPhone = true;\n",
    "          phoneStatus.push(`Col ${String.fromCharCode(65 + masterIdx)}: ${phone} (NEW)`);\n",
    "        } else {\n",
    "          targetRow[targetIdx] = ''; // Clear duplicate phone\n",
    "          phoneStatus.push(`Col ${String.fromCharCode(65 + masterIdx)}: ${phone} (DUPLICATE)`);\n",
    "        }\n",
    "      } else {\n",
    "        phoneStatus.push(`Col ${String.fromCharCode(65 + masterIdx)}: EMPTY`);\n",
    "      }\n",
    "    });\n",
    "\n",
    "\n",
    "    if (hasValidPhone) {\n",
    "      newRows.push(targetRow);\n",
    "    } else {\n",
    "      skippedLog.push(`Row ${i+1} skipped - All phones exist: ${phoneStatus.join(' | ')}`);\n",
    "    }\n",
    "  }\n",
    "\n",
    "\n",
    "  const startRow = 2;\n",
    "\n",
    "\n",
    "  if (newRows.length > 0) {\n",
    "    leadsSheet.getRange(2, 1, newRows.length, newRows[0].length)\n",
    "      .setValues(newRows);\n",
    "   \n",
    "    // Format date column (C)\n",
    "    leadsSheet.getRange(2, 3, newRows.length).setNumberFormat(\"dd/mm/yyyy\");\n",
    "  }\n",
    "\n",
    "\n",
    "  leadsSheet.getRange(startRow, 1, newRows.length, newRows[0].length)\n",
    "  .sort({ column: 3, ascending: true });\n",
    "\n",
    "\n",
    "    // Set VLOOKUP formula in column AB (28)\n",
    "  for (let i = 0; i < newRows.length; i++) {\n",
    "    const row = i + startRow;\n",
    "    const formula = `=IF(\n",
    "    COUNTIF({\n",
    "      IMPORTRANGE(\"1tQM2OplJqPHodWNyXDsQpyOJ7gHhC51Inar6njKH9Qk\", \"Shai Sheet!A:A\");\n",
    "      IMPORTRANGE(\"1tQM2OplJqPHodWNyXDsQpyOJ7gHhC51Inar6njKH9Qk\", \"Dominic Sheet!A:A\")\n",
    "    }, A${row}) > 1,\n",
    "    \"Duplicate\",\n",
    "    IFERROR(\n",
    "      VLOOKUP(A${row}, IMPORTRANGE(\"1tQM2OplJqPHodWNyXDsQpyOJ7gHhC51Inar6njKH9Qk\", \"Shai Sheet!A:AB\"), 28, FALSE),\n",
    "      IFERROR(\n",
    "        VLOOKUP(A${row}, IMPORTRANGE(\"1tQM2OplJqPHodWNyXDsQpyOJ7gHhC51Inar6njKH9Qk\", \"Dominic Sheet!A:AB\"), 28, FALSE),\n",
    "        \"Unassigned\"\n",
    "        )\n",
    "      )\n",
    "    )`;\n",
    "    leadsSheet.getRange(row, 28).setFormula(formula);\n",
    "      }\n",
    "   \n",
    "    Logger.log(`RESULTS\\nNew rows added: ${newRows.length}\\nSkipped rows: ${skippedLog.length}`);\n",
    "    console.log(`RESULTS\\nNew rows added: ${newRows.length}\\nSkipped rows: ${skippedLog.length}`);\n",
    "}\n",
    "\n",
    "\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "9e4640ef",
   "metadata": {},
   "outputs": [],
   "source": [
    "function syncLeadVerificationStatus() {\n",
    "  var masterSheet = SpreadsheetApp.openById(\"1ipwIl7fciIlddvOUqGLpNlVQufw7Xd26Qa-YuJcx-xE\")\n",
    "    .getSheetByName(\"MASTER DATABASE 2025 Template\");\n",
    "\n",
    "\n",
    "  var teleSalesFile = SpreadsheetApp.openById(\"1tQM2OplJqPHodWNyXDsQpyOJ7gHhC51Inar6njKH9Qk\");\n",
    "  var teleSalesSheets = [\n",
    "    teleSalesFile.getSheetByName(\"Shai Sheet\"),\n",
    "    teleSalesFile.getSheetByName(\"Dominic Sheet\")\n",
    "  ];\n",
    "\n",
    "\n",
    "  var masterData = masterSheet.getDataRange().getValues();\n",
    "\n",
    "\n",
    "  // Logging variables\n",
    "  var totalProcessed = 0;\n",
    "  var verifiedCount = 0;\n",
    "  var notVerifiedCount = 0;\n",
    "  var errors = [];\n",
    "\n",
    "\n",
    "  var outcomes = {};\n",
    "  for (var s = 0; s < teleSalesSheets.length; s++) {\n",
    "    var teleSalesData = teleSalesSheets[s].getDataRange().getValues();\n",
    "    for (var i = 1; i < teleSalesData.length; i++) { // Skip header row\n",
    "      try {\n",
    "        var leadCode = teleSalesData[i][0].toString().trim(); // Column A\n",
    "        var outcome = teleSalesData[i][29].toString().trim(); // Column AD (case preserved)\n",
    "        if (leadCode) {\n",
    "          outcomes[leadCode] = outcome;\n",
    "        }\n",
    "      } catch (e) {\n",
    "        errors.push(\"Error processing \" + teleSalesSheets[s].getName() + \" row \" + (i + 1) + \": \" + e.message);\n",
    "      }\n",
    "    }\n",
    "  }\n",
    "\n",
    "\n",
    "  for (var j = 1; j < masterData.length; j++) { // Skip header row\n",
    "    try {\n",
    "      var masterLeadCode = masterData[j][0].toString().trim(); // Column A\n",
    "      var statusCell = masterSheet.getRange(j + 1, 62); // Column BK\n",
    "     \n",
    "      var outcomeText = outcomes[masterLeadCode];\n",
    "      if (outcomeText) {\n",
    "        totalProcessed++;\n",
    "        var lowerOutcome = outcomeText.toLowerCase();\n",
    "\n",
    "\n",
    "        if (\n",
    "          lowerOutcome.includes(\"wrong number led to wrong business\") ||\n",
    "          lowerOutcome.includes(\"wrong number led to wrong person\") ||\n",
    "          lowerOutcome.includes(\"number not in use\") ||\n",
    "          lowerOutcome.includes(\"not existing number\")\n",
    "        ) {\n",
    "          statusCell.setValue(\"Not Verified\");\n",
    "          notVerifiedCount++;\n",
    "        } else {\n",
    "          statusCell.setValue(\"Verified\");\n",
    "          verifiedCount++;\n",
    "        }\n",
    "      }\n",
    "    } catch (e) {\n",
    "      errors.push(\"Error updating WB1 row \" + (j + 1) + \": \" + e.message);\n",
    "    }\n",
    "  }\n",
    "\n",
    "\n",
    "  var logMessage = [\n",
    "    \"RESULTS\",\n",
    "    \"Total leads processed: \" + totalProcessed,\n",
    "    \"Verified: \" + verifiedCount,\n",
    "    \"Not Verified: \" + notVerifiedCount,\n",
    "    \"\",\n",
    "    \"Errors (\" + errors.length + \"):\",\n",
    "    ...errors.slice(0, 10)\n",
    "  ].join(\"\\n\");\n",
    "\n",
    "\n",
    "  Logger.log(logMessage);\n",
    "}\n",
    "\n",
    "\n",
    "\n",
    "\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "dd3a9ae8",
   "metadata": {},
   "outputs": [],
   "source": [
    "function syncLeadVerificationStatus() {\n",
    "  var masterSheet = SpreadsheetApp.openById(\"1ipwIl7fciIlddvOUqGLpNlVQufw7Xd26Qa-YuJcx-xE\")\n",
    "    .getSheetByName(\"MASTER DATABASE 2025 Template\");\n",
    "\n",
    "\n",
    "  var teleSalesFile = SpreadsheetApp.openById(\"1tQM2OplJqPHodWNyXDsQpyOJ7gHhC51Inar6njKH9Qk\");\n",
    "  var teleSalesSheets = [\n",
    "    teleSalesFile.getSheetByName(\"Shai Sheet\"),\n",
    "    teleSalesFile.getSheetByName(\"Raj Sheet\"),\n",
    "    teleSalesFile.getSheetByName(\"Dominic Sheet\")\n",
    "  ];\n",
    "\n",
    "\n",
    "  var masterData = masterSheet.getDataRange().getValues();\n",
    "\n",
    "\n",
    "  // Logging variables\n",
    "  var totalProcessed = 0;\n",
    "  var verifiedCount = 0;\n",
    "  var notVerifiedCount = 0;\n",
    "  var errors = [];\n",
    "\n",
    "\n",
    "  var outcomes = {};\n",
    "  for (var s = 0; s < teleSalesSheets.length; s++) {\n",
    "    var teleSalesData = teleSalesSheets[s].getDataRange().getValues();\n",
    "    for (var i = 1; i < teleSalesData.length; i++) { // Skip header row\n",
    "      try {\n",
    "        var leadCode = teleSalesData[i][0].toString().trim(); // Column A\n",
    "        var outcome = teleSalesData[i][26].toString().trim().toLowerCase(); // Column AA\n",
    "        if (leadCode) {\n",
    "          outcomes[leadCode] = outcome;\n",
    "        }\n",
    "      } catch (e) {\n",
    "        errors.push(\"Error processing \" + teleSalesSheets[s].getName() + \" row \" + (i + 1) + \": \" + e.message);\n",
    "      }\n",
    "    }\n",
    "  }\n",
    "\n",
    "\n",
    "  for (var j = 1; j < masterData.length; j++) { // Skip header row\n",
    "    try {\n",
    "      var masterLeadCode = masterData[j][0].toString().trim(); // Column A\n",
    "      var statusCell = masterSheet.getRange(j + 1, 63); // Column BK\n",
    "     \n",
    "      if (masterLeadCode && outcomes[masterLeadCode]) {\n",
    "        totalProcessed++;\n",
    "        if (outcomes[masterLeadCode].includes(\"wrong number/number not in use\")) {\n",
    "          statusCell.setValue(\"Not Verified\");\n",
    "          notVerifiedCount++;\n",
    "        } else {\n",
    "          statusCell.setValue(\"Verified\");\n",
    "          verifiedCount++;\n",
    "        }\n",
    "      }\n",
    "    } catch (e) {\n",
    "      errors.push(\"Error updating WB1 row \" + (j + 1) + \": \" + e.message);\n",
    "    }\n",
    "  }\n",
    "\n",
    "\n",
    "  var logMessage = [\n",
    "    \"RESULTS\",\n",
    "    \"Total leads processed: \" + totalProcessed,\n",
    "    \"Verified: \" + verifiedCount,\n",
    "    \"Not Verified: \" + notVerifiedCount,\n",
    "    \"\",\n",
    "    \"Errors (\" + errors.length + \"):\",\n",
    "    ...errors.slice(0, 10)\n",
    "  ].join(\"\\n\");\n",
    "\n",
    "\n",
    "  Logger.log(logMessage);\n",
    "}\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "2dec35ba",
   "metadata": {},
   "outputs": [],
   "source": [
    "function copyDataToMaster() {\n",
    "  const ss = SpreadsheetApp.getActiveSpreadsheet();\n",
    "  const masterSheet = ss.getSheetByName(\"MASTER DATABASE 2025 Template\");\n",
    "  if (!masterSheet) throw new Error(\"Master sheet not found\");\n",
    "\n",
    "\n",
    "  const sheetNames = [\n",
    "    \"Kalaivani Sheet\",\n",
    "    \"Shafiqah Sheet\",\n",
    "    \"Kai Xin Sheet\",\n",
    "    \"Hazim Sheet\",\n",
    "    \"Khairunnisa Sheet\",\n",
    "    \"Jasmin Sheet\"\n",
    "  ];\n",
    "\n",
    "\n",
    "  const numCols = 62;\n",
    "  const masterData = masterSheet.getRange(2, 1, masterSheet.getLastRow() - 1, numCols).getValues();\n",
    "  const masterMap = {};\n",
    "  const copiedSheets = [];\n",
    "\n",
    "\n",
    "  for (let i = 0; i < masterData.length; i++) {\n",
    "    const key = String(masterData[i][0]).trim();\n",
    "    if (key) masterMap[key] = i + 2; // +2 for 1-based row and skipping header\n",
    "  }\n",
    "\n",
    "\n",
    "  for (const name of sheetNames) {\n",
    "    const sourceSheet = ss.getSheetByName(name);\n",
    "    if (!sourceSheet) {\n",
    "      Logger.log(`❌ Sheet not found: ${name}`);\n",
    "      continue;\n",
    "    }\n",
    "\n",
    "\n",
    "    const numRows = sourceSheet.getLastRow() - 1;\n",
    "    if (numRows <= 0) {\n",
    "      Logger.log(`No data in ${name}`);\n",
    "      continue;\n",
    "    }\n",
    "\n",
    "\n",
    "    const data = sourceSheet.getRange(2, 1, numRows, numCols).getValues();\n",
    "    const rowsToAppend = [];\n",
    "    let hasCopied = false;\n",
    "\n",
    "\n",
    "    for (let i = 0; i < data.length; i++) {\n",
    "      const rowData = data[i];\n",
    "      const key = String(rowData[0]).trim();\n",
    "\n",
    "\n",
    "      if (!key || rowData.filter(String).length <= 1) continue; // Skip empty or dummy rows\n",
    "\n",
    "\n",
    "      // Format date in Column B\n",
    "      if (rowData[2] instanceof Date) {\n",
    "        rowData[2] = Utilities.formatDate(new Date(rowData[2]), Session.getScriptTimeZone(), \"dd/MM/yyyy\");\n",
    "      }\n",
    "\n",
    "\n",
    "      if (masterMap[key]) {\n",
    "        masterSheet.getRange(masterMap[key], 1, 1, numCols).setValues([rowData]);\n",
    "        hasCopied = true;\n",
    "      } else {\n",
    "        rowsToAppend.push(rowData);\n",
    "        const newRowIndex = masterSheet.getLastRow() + rowsToAppend.length; // temporary until set\n",
    "        masterMap[key] = newRowIndex;\n",
    "        hasCopied = true;\n",
    "      }\n",
    "    }\n",
    "\n",
    "\n",
    "    // Batch append new rows\n",
    "    if (rowsToAppend.length > 0) {\n",
    "      masterSheet.getRange(masterSheet.getLastRow() + 1, 1, rowsToAppend.length, numCols).setValues(rowsToAppend);\n",
    "    }\n",
    "\n",
    "\n",
    "    if (hasCopied) {\n",
    "      copiedSheets.push(name);\n",
    "    }\n",
    "  }\n",
    "\n",
    "\n",
    "  // Final sort by ePOS Code\n",
    "  const finalRow = masterSheet.getLastRow();\n",
    "  if (finalRow > 1) {\n",
    "    masterSheet.getRange(2, 1, finalRow - 1, numCols).sort({ column: 1, ascending: true });\n",
    "  }\n",
    "\n",
    "\n",
    "  Logger.log(\"✅ Data transfer complete.\");\n",
    "  Logger.log(\"Data copied from sheets: \" + (copiedSheets.length ? copiedSheets.join(\", \") : \"None\"));\n",
    "}\n",
    "\n",
    "\n",
    "\n",
    "\n",
    "\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "c9fac826",
   "metadata": {},
   "outputs": [],
   "source": [
    "function onEdit(e) { //\"oneEdit(e)\": Runs functions when someone edit a cell\n",
    "  if (!e) return; // prevent manual execution error, ensures the script doesn't crash when that happens.\n",
    "\n",
    "\n",
    "//  Set configuration for your use case\n",
    "  const validSheets = [\"Kai Xin Sheet\", \"Kalaivani Sheet\", \"Shafiqah Sheet\", \"Hazim Sheet\", \"Khairunissa Sheet\", \"Amirah Sheet\"];\n",
    "  const regionCol = 31;\n",
    "  const planningAreaCol = 32;\n",
    "  const parentindustryCol = 25;\n",
    "  const industrytypeCol = 26;\n",
    "  const subindustryCol = 27;\n",
    "\n",
    "\n",
    "  // Identify what and where was edited\n",
    "  const sheet = e.range.getSheet();\n",
    "  const range = e.range;\n",
    "\n",
    "\n",
    "  if (validSheets.includes(sheet.getName()) && range.getColumn() === regionCol) { //Check if the edit happened in the correct sheet & column\n",
    "    const region = range.getValue(); //Reads the selected Region from the edited cell.\n",
    "    Logger.log('Region selected: ' + region);\n",
    "\n",
    "\n",
    "    // Load reference data (Region → Planning Area map)\n",
    "    const refSheet = e.source.getSheetByName('Zones & Planning Area');\n",
    "    const data = refSheet.getRange(2, 1, refSheet.getLastRow() - 1, 2).getValues();\n",
    "\n",
    "\n",
    "    // Filter Planning Areas for the selected Region\n",
    "    const planningAreas = data\n",
    "      .filter(row => row[0] === region) // match selected region\n",
    "      .map(row => row[1]) //// get planning area\n",
    "      .filter((item, pos, arr) => arr.indexOf(item) === pos); //// remove duplicates\n",
    "\n",
    "\n",
    "    const planningAreaCell = sheet.getRange(range.getRow(), planningAreaCol); // Define the Planning Area cell to update\n",
    "\n",
    "\n",
    "    //Add dropdown validation for Planning Area\n",
    "    if (planningAreas.length > 0) {\n",
    "      const rule = SpreadsheetApp.newDataValidation()\n",
    "        .requireValueInList(planningAreas, true) // allow dropdown options\n",
    "        .setAllowInvalid(false) // disallow invalid input\n",
    "        .build();\n",
    "\n",
    "\n",
    "      planningAreaCell.clearDataValidations(); // remove old rule\n",
    "      planningAreaCell.setDataValidation(rule); // add new rule\n",
    "      planningAreaCell.clearContent(); // clear previous value\n",
    "    } else { //If region is blank or has no matches — clear dropdown\n",
    "      planningAreaCell.clearDataValidations();\n",
    "      planningAreaCell.clearContent();\n",
    "    }\n",
    "  }\n",
    "\n",
    "\n",
    "  // Parent Industry → Industry Type map\n",
    "  if (validSheets.includes(sheet.getName()) && range.getColumn() === parentindustryCol) {\n",
    "    const parentindustry = range.getValue();\n",
    "    Logger.log('parent industry selected: ' + parentindustry);\n",
    "\n",
    "\n",
    "    const refSheet = e.source.getSheetByName('Bifurcation of Sub Industry');\n",
    "    const data = refSheet.getRange(2, 1, refSheet.getLastRow() - 1, 2).getValues();\n",
    "\n",
    "\n",
    "    const industrytype = data\n",
    "      .filter(row => row[0] === parentindustry)\n",
    "      .map(row => row[1])\n",
    "      .filter((item, pos, arr) => arr.indexOf(item) === pos);\n",
    "\n",
    "\n",
    "    const industrytypeCell = sheet.getRange(range.getRow(), industrytypeCol);\n",
    "    const subindustryCell = sheet.getRange(range.getRow(), subindustryCol);\n",
    "\n",
    "\n",
    "    if (industrytype.length > 0) {\n",
    "      const rule = SpreadsheetApp.newDataValidation()\n",
    "        .requireValueInList(industrytype, true)\n",
    "        .setAllowInvalid(false)\n",
    "        .build();\n",
    "\n",
    "\n",
    "      industrytypeCell.clearDataValidations();\n",
    "      industrytypeCell.setDataValidation(rule);\n",
    "      industrytypeCell.clearContent();\n",
    "      subindustryCell.clearDataValidations();  \n",
    "      subindustryCell.clearContent();\n",
    "    } else {\n",
    "      industrytypeCell.clearDataValidations();\n",
    "      industrytypeCell.clearContent();\n",
    "    }\n",
    "  }\n",
    "\n",
    "\n",
    "  // Industry Type → Sub Industry map\n",
    "  if (validSheets.includes(sheet.getName()) && range.getColumn() === industrytypeCol) {\n",
    "    const industrytype = range.getValue();\n",
    "    Logger.log('industry type selected: ' + industrytype);\n",
    "\n",
    "\n",
    "    // Load reference data (Region → Planning Area map)\n",
    "    const refSheet = e.source.getSheetByName('Bifurcation of Sub Industry');\n",
    "    const data = refSheet.getRange(2, 2, refSheet.getLastRow() - 1, 2).getValues();\n",
    "\n",
    "\n",
    "    const subindustry = data\n",
    "      .filter(row => row[0] === industrytype)\n",
    "      .map(row => row[1])\n",
    "      .filter((item, pos, arr) => arr.indexOf(item) === pos);\n",
    "\n",
    "\n",
    "    const subindustryCell = sheet.getRange(range.getRow(), subindustryCol);\n",
    "\n",
    "\n",
    "    //Add dropdown validation for Planning Area\n",
    "    if (subindustry.length > 0) {\n",
    "      const rule = SpreadsheetApp.newDataValidation()\n",
    "        .requireValueInList(subindustry, true) // allow dropdown options\n",
    "        .setAllowInvalid(false) // disallow invalid input\n",
    "        .build();\n",
    "\n",
    "\n",
    "      subindustryCell.clearDataValidations(); // remove old rule\n",
    "      subindustryCell.setDataValidation(rule); // add new rule\n",
    "      subindustryCell.clearContent(); // clear previous value\n",
    "    } else { //If region is blank or has no matches — clear dropdown\n",
    "      subindustryCell.clearDataValidations();\n",
    "      subindustryCell.clearContent();\n",
    "    }\n",
    "  }\n",
    "   \n",
    "}\n",
    "\n",
    "\n",
    "\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "72523cf2",
   "metadata": {},
   "outputs": [],
   "source": [
    "function copyUniqueLeads() {\n",
    "  const ss = SpreadsheetApp.getActiveSpreadsheet();\n",
    "  const masterSheet = ss.getSheetByName(\"MASTER DATABASE 2025 Template\");\n",
    "  const leadsSheet = ss.getSheetByName(\"Non-Repeated Leads for Shai\");\n",
    "\n",
    "\n",
    "  if (leadsSheet.getLastRow() > 1) {\n",
    "      // Clear all except column Y (25)\n",
    "    leadsSheet.getRange(2, 1, leadsSheet.getLastRow() - 1, 24).clearContent();\n",
    "    const remainingCols = leadsSheet.getLastColumn() - 25;\n",
    "    if (remainingCols > 0) {\n",
    "      leadsSheet.getRange(2, 26, leadsSheet.getLastRow() - 1, remainingCols).clearContent();\n",
    "    }\n",
    "  }\n",
    "\n",
    "\n",
    "  // Column mapping [MASTER index → TARGET index]\n",
    "  const COLUMN_MAP = [\n",
    "    [0, 0],   // A → A\n",
    "    [1, 1],   // B → B\n",
    "    [2, 2],   // C → C (date)\n",
    "    [3, 3],   // D → D (Acra Registered Name)\n",
    "    [4, 4],   // E → E (FIXED)\n",
    "    [7, 5],   // H → F\n",
    "    [27, 6],  // AB → G\n",
    "    [41, 7],  // AP → H\n",
    "    [42, 8],  // AQ → I\n",
    "    [43, 9],  // AR → J\n",
    "    [44, 10],  // AS → K (Phone 1)\n",
    "    [45, 11], // AT → L\n",
    "    [46, 12], // AU → M\n",
    "    [47, 13], // AV → N\n",
    "    [48, 14], // AW → O (PIC 2 Designation)\n",
    "    [49, 15], // AX → P (Phone 2)\n",
    "    [50, 16], // AY → Q\n",
    "    [51, 17], // AZ → R\n",
    "    [52, 18], // BA → S\n",
    "    [53, 19], // BB → T (PIC 3 Designation)\n",
    "    [54, 20], // BC → U (Phone 3)\n",
    "    [55, 21], // BD → V\n",
    "    [57, 22], // BF → W (EPOS CLIENTS)\n",
    "    [58, 23], // BG → X (PLUGINS)\n",
    "  ];\n",
    "\n",
    "\n",
    "  // Phone columns to check for duplicates [MASTER index, TARGET index]\n",
    "  const PHONE_COLS = [[44,10], [49,15], [54,20]]; // AR/J, AW/O, BB/T\n",
    "\n",
    "\n",
    "  const masterData = masterSheet.getDataRange().getValues();\n",
    "  const globalPhones = new Set();\n",
    "  const newRows = [];\n",
    "  const skippedLog = [];\n",
    "\n",
    "\n",
    "  const targetData = leadsSheet.getRange(1, 1, leadsSheet.getLastRow(), leadsSheet.getLastColumn()).getValues();\n",
    "  for (let i = 1; i < targetData.length; i++) {\n",
    "    PHONE_COLS.forEach(([_, targetIdx]) => {\n",
    "      const phone = targetData[i][targetIdx]?.toString().trim();\n",
    "      if (phone) globalPhones.add(phone);\n",
    "    });\n",
    "  }\n",
    "\n",
    "\n",
    "  // Process master data\n",
    "  for (let i = 1; i < masterData.length; i++) {\n",
    "    const masterRow = masterData[i];\n",
    "    const targetRow = Array(24).fill(''); // Adjust if target has more columns\n",
    "   \n",
    "    // Copy mapped columns\n",
    "    COLUMN_MAP.forEach(([masterIdx, targetIdx]) => {\n",
    "      targetRow[targetIdx] = masterRow[masterIdx] !== undefined ? masterRow[masterIdx] : '';\n",
    "    });\n",
    "\n",
    "\n",
    "    // Check unique phone num\n",
    "    let hasValidPhone = false;\n",
    "    const phoneStatus = [];\n",
    "   \n",
    "    PHONE_COLS.forEach(([masterIdx, targetIdx]) => {\n",
    "      const rawPhone = masterRow[masterIdx];\n",
    "      const phone = rawPhone ? rawPhone.toString().replace(/[\\s\\-]/g, '').trim() : '';\n",
    "     \n",
    "      if (phone) {\n",
    "        if (!globalPhones.has(phone)) {\n",
    "          globalPhones.add(phone);\n",
    "          hasValidPhone = true;\n",
    "          phoneStatus.push(`Col ${String.fromCharCode(65 + masterIdx)}: ${phone} (NEW)`);\n",
    "        } else {\n",
    "          targetRow[targetIdx] = ''; // Clear duplicate phone\n",
    "          phoneStatus.push(`Col ${String.fromCharCode(65 + masterIdx)}: ${phone} (DUPLICATE)`);\n",
    "        }\n",
    "      } else {\n",
    "        phoneStatus.push(`Col ${String.fromCharCode(65 + masterIdx)}: EMPTY`);\n",
    "      }\n",
    "    });\n",
    "\n",
    "\n",
    "    if (hasValidPhone) {\n",
    "      newRows.push(targetRow);\n",
    "    } else {\n",
    "      skippedLog.push(`Row ${i+1} skipped - All phones exist: ${phoneStatus.join(' | ')}`);\n",
    "    }\n",
    "  }\n",
    "\n",
    "\n",
    "  const startRow = 2;\n",
    "\n",
    "\n",
    "  if (newRows.length > 0) {\n",
    "    leadsSheet.getRange(2, 1, newRows.length, newRows[0].length)\n",
    "      .setValues(newRows);\n",
    "   \n",
    "    // Format date column (C)\n",
    "    leadsSheet.getRange(2, 3, newRows.length).setNumberFormat(\"dd/mm/yyyy\");\n",
    "  }\n",
    "\n",
    "\n",
    "  leadsSheet.getRange(startRow, 1, newRows.length, newRows[0].length)\n",
    "  .sort({ column: 3, ascending: true });\n",
    "\n",
    "\n",
    "    // Set VLOOKUP formula in column Y (25)\n",
    "  for (let i = 0; i < newRows.length; i++) {\n",
    "    const row = i + startRow;\n",
    "    const formula = `=IF(\n",
    "      COUNTIF({\n",
    "       IMPORTRANGE(\"1tQM2OplJqPHodWNyXDsQpyOJ7gHhC51Inar6njKH9Qk\", \"Shai Sheet!A:A\");\n",
    "       IMPORTRANGE(\"1tQM2OplJqPHodWNyXDsQpyOJ7gHhC51Inar6njKH9Qk\", \"Raj Sheet!A:A\");\n",
    "       IMPORTRANGE(\"1tQM2OplJqPHodWNyXDsQpyOJ7gHhC51Inar6njKH9Qk\", \"Dominic Sheet!A:A\")\n",
    "       }, A${row}) > 1,\n",
    "       \"Duplicate\",\n",
    "       IFERROR(\n",
    "        VLOOKUP(A${row}, IMPORTRANGE(\"1tQM2OplJqPHodWNyXDsQpyOJ7gHhC51Inar6njKH9Qk\", \"Shai Sheet!A:Y\"), 25, FALSE),\n",
    "        IFERROR(\n",
    "          VLOOKUP(A${row}, IMPORTRANGE(\"1tQM2OplJqPHodWNyXDsQpyOJ7gHhC51Inar6njKH9Qk\", \"Raj Sheet!A:Y\"), 25, FALSE),\n",
    "          IFERROR(\n",
    "            VLOOKUP(A${row}, IMPORTRANGE(\"1tQM2OplJqPHodWNyXDsQpyOJ7gHhC51Inar6njKH9Qk\", \"Dominic Sheet!A:Y\"), 25, FALSE),\n",
    "            \"Unassigned\"\n",
    "          )\n",
    "        )\n",
    "      )\n",
    "    )`;\n",
    "    leadsSheet.getRange(row, 25).setFormula(formula);\n",
    "      }\n",
    "   \n",
    "    Logger.log(`RESULTS\\nNew rows added: ${newRows.length}\\nSkipped rows: ${skippedLog.length}`);\n",
    "    console.log(`RESULTS\\nNew rows added: ${newRows.length}\\nSkipped rows: ${skippedLog.length}`);\n",
    "}\n",
    "\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "ca571f36",
   "metadata": {},
   "outputs": [],
   "source": [
    "function onEdit(e) {\n",
    "  if (!e) return;\n",
    "\n",
    "\n",
    "  const validSheets = [\"Shai Sheet\", \"Dominic Sheet\", \"Vincy Sheet\", \"Victoria Sheet\", \"Farisi Sheet\"];\n",
    "  const CallCol = 30;\n",
    "  const DemoCol = 31;\n",
    "  const SalesCol = 32;\n",
    "\n",
    "\n",
    "  const sheet = e.range.getSheet();\n",
    "  const row = e.range.getRow();\n",
    "  const col = e.range.getColumn();\n",
    "\n",
    "\n",
    "  if (!validSheets.includes(sheet.getName())) return;\n",
    "\n",
    "\n",
    "  const Call = sheet.getRange(row, CallCol).getValue();\n",
    "  const Demo = sheet.getRange(row, DemoCol).getValue();\n",
    "  const Sales = sheet.getRange(row, SalesCol).getValue();\n",
    "\n",
    "\n",
    "  const DemoCell = sheet.getRange(row, DemoCol);\n",
    "  const SalesCell = sheet.getRange(row, SalesCol);\n",
    "\n",
    "\n",
    "  const forceBlankCol27 = [\"Line Busy/ Switched Off\", \"No Answer\", \"Not Interested\", \"Hang Up\", \"Left the Company\", \"Business Shut Down\", \"Contact Later/Future Opportunity\", \"Duplication\",\"Wrong Number led to Wrong Person\", \"Number not in Use/Not Existing Number\", \"DNC – Do Not Call (Customer Request)\"];\n",
    "  const allowedDemo = \"Fixed\";\n",
    "  const allowedCall = [\"Connected\", \"Wrong Number led to Wrong Business\", \"Opened New Business\" , \"Contacted via WA only\", \"Language Barrier\"];\n",
    "  const alertColor = \"#f4cccc\"; // light red\n",
    "  const normalColor = null; // reset color\n",
    "\n",
    "\n",
    "  // --- Column 27 logic (Call Outcome) ---\n",
    "  if (col === CallCol) {\n",
    "    if (forceBlankCol27.includes(Call)) {\n",
    "      DemoCell.clearContent().clearDataValidations();\n",
    "      SalesCell.clearContent().clearDataValidations().setBackground(normalColor);\n",
    "      return;\n",
    "    }\n",
    "\n",
    "\n",
    "    const refSheet = e.source.getSheetByName('Call to Sales Won Pipeline');\n",
    "    const data = refSheet.getRange(2, 1, refSheet.getLastRow() - 1, 2).getValues();\n",
    "\n",
    "\n",
    "    const DemoOptions = [...new Set(data\n",
    "      .filter(row => row[0] === Call)\n",
    "      .map(row => row[1]))];\n",
    "\n",
    "\n",
    "    if (DemoOptions.length > 0) {\n",
    "      const rule = SpreadsheetApp.newDataValidation()\n",
    "        .requireValueInList(DemoOptions, true)\n",
    "        .setAllowInvalid(false)\n",
    "        .build();\n",
    "      DemoCell.clearDataValidations().setDataValidation(rule).clearContent();\n",
    "      SalesCell.clearDataValidations().clearContent().setBackground(normalColor);\n",
    "    } else {\n",
    "      DemoCell.clearDataValidations().clearContent();\n",
    "      SalesCell.clearDataValidations().clearContent().setBackground(normalColor);\n",
    "    }\n",
    "  }\n",
    "\n",
    "\n",
    "  // --- Column 28 logic (Demo Outcome) ---\n",
    "  if (col === DemoCol) {\n",
    "    if (forceBlankCol27.includes(Call)) {\n",
    "      DemoCell.clearContent();\n",
    "      return;\n",
    "    }\n",
    "\n",
    "\n",
    "    if (Demo !== allowedDemo) {\n",
    "      SalesCell.clearContent().clearDataValidations().setBackground(normalColor);\n",
    "      return;\n",
    "    }\n",
    "\n",
    "\n",
    "    const refSheet = e.source.getSheetByName('Call to Sales Won Pipeline');\n",
    "    const data = refSheet.getRange(2, 2, refSheet.getLastRow() - 1, 2).getValues();\n",
    "\n",
    "\n",
    "    const SalesOptions = [...new Set(data\n",
    "      .filter(row => row[0] === Demo)\n",
    "      .map(row => row[1]))];\n",
    "\n",
    "\n",
    "    if (SalesOptions.length > 0) {\n",
    "      const rule = SpreadsheetApp.newDataValidation()\n",
    "        .requireValueInList(SalesOptions, true)\n",
    "        .setAllowInvalid(false)\n",
    "        .build();\n",
    "      SalesCell.clearDataValidations().setDataValidation(rule).clearContent().setBackground(alertColor);\n",
    "    } else {\n",
    "      SalesCell.clearDataValidations().clearContent().setBackground(normalColor);\n",
    "    }\n",
    "  }\n",
    "\n",
    "\n",
    "  // --- Force blank logic ---\n",
    "  if ((col === DemoCol || col === SalesCol) && forceBlankCol27.includes(Call)) {\n",
    "    sheet.getRange(row, col).clearContent();\n",
    "    SalesCell.setBackground(normalColor);\n",
    "    return;\n",
    "  }\n",
    "\n",
    "\n",
    "  if (col === SalesCol && Demo !== allowedDemo) {\n",
    "    SalesCell.clearContent().setBackground(normalColor);\n",
    "    return;\n",
    "  }\n",
    "\n",
    "\n",
    "  // --- Background reminder: If 28 = Fixed and 29 is blank, highlight red ---\n",
    "  if (Demo === allowedDemo) {\n",
    "    if (!Sales) {\n",
    "      SalesCell.setBackground(alertColor);\n",
    "    } else {\n",
    "      SalesCell.setBackground(normalColor);\n",
    "    }\n",
    "  }\n",
    "\n",
    "\n",
    "}\n",
    "\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "a2184254",
   "metadata": {},
   "outputs": [],
   "source": [
    "=OR(LEN(L2)=0, COUNTIF({   'Shafiqah Sheet'!L$2:L;   'Kalaivani Sheet'!L$2:L;   'Kai Xin Sheet'!L$2:L;   'Hazim Sheet'!L$2:L;   'Khairunnisa Sheet'!L$2:L;   'Jasmin Sheet'!L$2:L;   'Suen Xemin Sheet'!L$2:L;   'Peng Tee Sheet'!L$2:L;   'Nabihah Sheet'!L$2:L }, L2)=0)\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "213b91a6",
   "metadata": {},
   "outputs": [],
   "source": [
    "function copyUniqueLeads() {\n",
    "  const ss = SpreadsheetApp.getActiveSpreadsheet();\n",
    "  const masterSheet = ss.getSheetByName(\"MASTER DATABASE 2025 Template\");\n",
    "  const leadsSheet = ss.getSheetByName(\"Non-Repeated Leads for TS\");\n",
    "\n",
    "\n",
    "  const DATE_COLUMN_INDEX = 2; // Column C is at index 2 (0-indexed)\n",
    "\n",
    "\n",
    "  if (leadsSheet.getLastRow() > 1) {\n",
    "    // Clear all except column AB (28)\n",
    "    leadsSheet.getRange(2, 1, leadsSheet.getLastRow() - 1, 27).clearContent();\n",
    "    const remainingCols = leadsSheet.getLastColumn() - 28;\n",
    "    if (remainingCols > 0) {\n",
    "      leadsSheet.getRange(2, 29, leadsSheet.getLastRow() - 1, remainingCols).clearContent();\n",
    "    }\n",
    "  }\n",
    "\n",
    "\n",
    "  // Column mapping [MASTER index → TARGET index]\n",
    "  const COLUMN_MAP = [\n",
    "    [0, 0],    // A → A\n",
    "    [1, 1],    // B → B\n",
    "    [2, 2],    // C → C (date)\n",
    "    [3, 3],    // D → D (Acra Registered Name)\n",
    "    [4, 4],    // E → E (FIXED)\n",
    "    [7, 5],    // H → F\n",
    "    [26, 6],   // AA → G (sub-industry)\n",
    "    [18, 7],   // S → H (biz type)\n",
    "    [23, 8],   // X → I (ownership type)\n",
    "    [27, 9],   // AB → J (biz model)\n",
    "    [40, 10],  // AO → K\n",
    "    [41, 11],  // AP → L\n",
    "    [42, 12],  // AQ → M\n",
    "    [43, 13],  // AR → N (Phone 1)\n",
    "    [44, 14],  // AS → O\n",
    "    [45, 15],  // AT → P\n",
    "    [46, 16],  // AU → Q\n",
    "    [47, 17],  // AV → R (PIC 2 Designation)\n",
    "    [48, 18],  // AW → S (Phone 2)\n",
    "    [49, 19],  // AX → T (PIC 3 Designation)\n",
    "    [50, 20],  // AY → U\n",
    "    [51, 21],  // AZ → V\n",
    "    [52, 22],  // BA → W\n",
    "    [53, 23],  // BB → X (Phone 3)\n",
    "    [54, 24],  // BC → Y\n",
    "    [56, 25],  // BE → Z\n",
    "    [57, 26],  // BF → AA\n",
    "  ];\n",
    "\n",
    "\n",
    "  // Phone columns to check for duplicates [MASTER index, TARGET index]\n",
    "  const PHONE_COLS = [[43, 13], [48, 18], [53, 23]]; // AR/N, AW/S, BB/X\n",
    "\n",
    "\n",
    "  const masterData = masterSheet.getDataRange().getValues();\n",
    "  const globalPhones = new Set();\n",
    "  const newRows = [];\n",
    "  const skippedLog = [];\n",
    "\n",
    "\n",
    "  const targetData = leadsSheet.getRange(1, 1, leadsSheet.getLastRow(), leadsSheet.getLastColumn()).getValues();\n",
    "  for (let i = 1; i < targetData.length; i++) {\n",
    "    PHONE_COLS.forEach(([_, targetIdx]) => {\n",
    "      const phone = targetData[i][targetIdx]?.toString().trim();\n",
    "      if (phone) globalPhones.add(phone);\n",
    "    });\n",
    "  }\n",
    "\n",
    "\n",
    "  // Process master data\n",
    "  for (let i = 1; i < masterData.length; i++) {\n",
    "    const masterRow = masterData[i];\n",
    "    const targetRow = Array(27).fill(''); // Adjust if target has more columns\n",
    "   \n",
    "    // Copy mapped columns\n",
    "    COLUMN_MAP.forEach(([masterIdx, targetIdx]) => {\n",
    "      targetRow[targetIdx] = masterRow[masterIdx] !== undefined ? masterRow[masterIdx] : '';\n",
    "    });\n",
    "\n",
    "\n",
    "    // Check unique phone num\n",
    "    let hasValidPhone = false;\n",
    "    const phoneStatus = [];\n",
    "   \n",
    "    PHONE_COLS.forEach(([masterIdx, targetIdx]) => {\n",
    "      const rawPhone = masterRow[masterIdx];\n",
    "      const phone = rawPhone ? rawPhone.toString().replace(/[\\s\\-]/g, '').trim() : '';\n",
    "     \n",
    "      if (phone) {\n",
    "        if (!globalPhones.has(phone)) {\n",
    "          globalPhones.add(phone);\n",
    "          hasValidPhone = true;\n",
    "          phoneStatus.push(`Col ${String.fromCharCode(65 + masterIdx)}: ${phone} (NEW)`);\n",
    "        } else {\n",
    "          targetRow[targetIdx] = ''; // Clear duplicate phone\n",
    "          phoneStatus.push(`Col ${String.fromCharCode(65 + masterIdx)}: ${phone} (DUPLICATE)`);\n",
    "        }\n",
    "      } else {\n",
    "        phoneStatus.push(`Col ${String.fromCharCode(65 + masterIdx)}: EMPTY`);\n",
    "      }\n",
    "    });\n",
    "\n",
    "\n",
    "    if (hasValidPhone) {\n",
    "      newRows.push(targetRow);\n",
    "    } else {\n",
    "      skippedLog.push(`Row ${i + 1} skipped - All phones exist: ${phoneStatus.join(' | ')}`);\n",
    "    }\n",
    "  }\n",
    " \n",
    "  // --- START OF FIX ---\n",
    "  // Convert date values to Date objects for proper sorting\n",
    "  newRows.forEach(row => {\n",
    "    const dateValue = row[DATE_COLUMN_INDEX];\n",
    "    // Check if the value is already a Date object\n",
    "    if (Object.prototype.toString.call(dateValue) !== '[object Date]') {\n",
    "      // If not, try to parse it from a string (assuming dd/mm/yyyy format)\n",
    "      const parts = dateValue?.toString().split('/');\n",
    "      if (parts && parts.length === 3) {\n",
    "        // Create a new Date object (month is 0-indexed)\n",
    "        const d = new Date(parts[2], parts[1] - 1, parts[0]);\n",
    "        // Check if the date is valid before setting it\n",
    "        if (!isNaN(d.getTime())) {\n",
    "          row[DATE_COLUMN_INDEX] = d;\n",
    "        }\n",
    "      }\n",
    "    }\n",
    "  });\n",
    "\n",
    "\n",
    "  const startRow = 2;\n",
    "\n",
    "\n",
    "  if (newRows.length > 0) {\n",
    "    // Now, the date column contains valid Date objects, so sorting will work.\n",
    "    leadsSheet.getRange(2, 1, newRows.length, newRows[0].length).setValues(newRows);\n",
    "   \n",
    "    // Sort the data. The column 3 in the sort method is 1-indexed, which corresponds to column C.\n",
    "    leadsSheet.getRange(startRow, 1, newRows.length, newRows[0].length).sort({ column: 3, ascending: true });\n",
    "  }\n",
    "\n",
    "\n",
    "  // --- END OF FIX ---\n",
    "\n",
    "\n",
    "  const formulas = [];\n",
    "  for (let i = 0; i < newRows.length; i++) {\n",
    "    const row = i + startRow;\n",
    "    const formula = `=IF(\n",
    "    COUNTIF({\n",
    "      IMPORTRANGE(\"1tQM2OplJqPHodWNyXDsQpyOJ7gHhC51Inar6njKH9Qk\", \"Shai Sheet!A:A\");\n",
    "      IMPORTRANGE(\"1tQM2OplJqPHodWNyXDsQpyOJ7gHhC51Inar6njKH9Qk\", \"Dominic Sheet!A:A\")\n",
    "    }, A${row}) > 1,\n",
    "    \"Duplicate\",\n",
    "    IFERROR(\n",
    "      VLOOKUP(A${row}, IMPORTRANGE(\"1tQM2OplJqPHodWNyXDsQpyOJ7gHhC51Inar6njKH9Qk\", \"Shai Sheet!A:AB\"), 28, FALSE),\n",
    "      IFERROR(\n",
    "        VLOOKUP(A${row}, IMPORTRANGE(\"1tQM2OplJqPHodWNyXDsQpyOJ7gHhC51Inar6njKH9Qk\", \"Dominic Sheet!A:AB\"), 28, FALSE),\n",
    "        \"Unassigned\"\n",
    "        )\n",
    "      )\n",
    "    )`;\n",
    "    formulas.push([formula]);\n",
    "  }\n",
    "\n",
    "\n",
    "  if (formulas.length > 0) {\n",
    "    leadsSheet.getRange(startRow, 28, formulas.length, 1).setFormulas(formulas);\n",
    "  }\n",
    "   \n",
    "  Logger.log(`RESULTS\\nNew rows added: ${newRows.length}\\nSkipped rows: ${skippedLog.length}`);\n",
    "  console.log(`RESULTS\\nNew rows added: ${newRows.length}\\nSkipped rows: ${skippedLog.length}`);\n",
    "}\n",
    "\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "9ccf012f",
   "metadata": {},
   "outputs": [],
   "source": [
    "/**\n",
    " * Processes a form submission, generates a correctly mapped prefilled Admin Form URL,\n",
    " * and sends a simplified email notification to the Sales Admin.\n",
    " *\n",
    " * FINAL CORRECTED VERSION as of Oct 7, 2025\n",
    " */\n",
    "function onFormSubmit(e) {\n",
    "  // === FORM URLs ===\n",
    "  const form2BaseURL = \"https://docs.google.com/forms/d/e/1FAIpQLSeGUFVY6Mg8xrAfGIZo6guagFJPqCrS26GLMuz5pb8tbH7Gkg/viewform\"; // Admin Form\n",
    "\n",
    "\n",
    "  const sheet = e.source.getActiveSheet();\n",
    "  const row = e.range.getRow();\n",
    "  const data = sheet.getRange(row, 1, 1, sheet.getLastColumn()).getValues()[0];\n",
    "  const timezone = Session.getScriptTimeZone();\n",
    "\n",
    "\n",
    "  // === Column mapping from Form 1 submission ===\n",
    "  const dealType = data[1]; // B: Is this a New Deal or Follow-Up?\n",
    "  const ownLead = data[2]; // C: Own lead?\n",
    " \n",
    "  // New Deal Client Info\n",
    "  const clientName = data[3]; // D: Client's Name\n",
    "  const clientContact = data[4]; // E: Client's Contact Number\n",
    "\n",
    "\n",
    "  // New Deal Primary Info\n",
    "  const leadHandledBy = data[5]; // F: Lead Handled By\n",
    "  const demoDateObject = data[6]; // G: Demo Date\n",
    "  const companyName = data[7]; // H: Company Name\n",
    "\n",
    "\n",
    "  // New Deal Deal Info\n",
    "  const contactId = data[8]; // I: Contact ID\n",
    "  const businessDescription = data[9]; // J: Business Description\n",
    "  const proposedProductsRaw = data[10]; // K: Proposed Products\n",
    "  const amount = data[11]; // L: Amount\n",
    "  const stage = data[12]; // M: Stage\n",
    "  const pipeline = data[13]; // N: Pipeline\n",
    "  const statusNextStep = data[14]; // O: Status / Next Step\n",
    "  const extraNotes = data[15]; // P: Extra Notes\n",
    " \n",
    "  // Follow Up Info\n",
    "  const leadHandledByFU = data[16]; // Q: Lead Handled By - Follow Up\n",
    "  const companyNameFU = data[17]; // R: Company Name - Follow Up\n",
    "  const demoDateObjectFU = data[18]; // S: Demo Date - Follow Up\n",
    "  const dealNameFU = data[19]; // T: Deal Name - Follow Up\n",
    "  const dealIdFU = data[20]; // U: Deal ID - Follow Up\n",
    "  const pipelineFU = data[21]; // V: Pipeline - Follow Up\n",
    "  const stageFU = data[22]; // W: Stage - Follow Up\n",
    "\n",
    "\n",
    "\n",
    "\n",
    "  // === Form 2 Entry IDs (FULLY REBUILT AND VERIFIED from your pre-filled link) ===\n",
    "  const entry = {\n",
    "    // New Deal Section\n",
    "    dealType: \"entry.2071997062\",\n",
    "    ownLead: \"entry.1083003112\",\n",
    "    clientName: \"entry.26935909\",\n",
    "    clientContact: \"entry.316118767\",\n",
    "    leadHandledBy: \"entry.1552010076\",\n",
    "    demoDate: \"entry.485184656\",\n",
    "    companyName: \"entry.747743425\",\n",
    "    contactId: \"entry.1500102663\", // <-- CORRECT ID FOUND!\n",
    "    businessDescription: \"entry.859093337\",\n",
    "    proposedProducts: \"entry.747202753\",\n",
    "    amount: \"entry.1807194519\",\n",
    "    pipeline: \"entry.707684888\",\n",
    "    stage: \"entry.1276752414\",\n",
    "   \n",
    "    // Follow-up Section  \n",
    "    leadHandledByFU: \"entry.336935324\",\n",
    "    companyNameFU: \"entry.484707040\",\n",
    "    dealNameFU: \"entry.113619823\",\n",
    "    dealIdFU: \"entry.416384083\",\n",
    "    demoDateFU: \"entry.1224456152\",\n",
    "    pipelineFU: \"entry.1349517226\",\n",
    "    stageFU: \"entry.1667620792\",\n",
    "   \n",
    "    // Common fields for both sections\n",
    "    status: \"entry.2048318253\",\n",
    "    notes: \"entry.471781032\"\n",
    "  };\n",
    "\n",
    "\n",
    "  // === Clean and format data ===\n",
    "  let ownLeadValue = String(ownLead || \"\").trim().toLowerCase();\n",
    "  if ([\"yes\", \"y\", \"true\", \"own lead\"].includes(ownLeadValue)) {\n",
    "    ownLeadValue = \"Yes\";\n",
    "  } else {\n",
    "    ownLeadValue = \"No\";\n",
    "  }\n",
    "\n",
    "\n",
    "  const demoDate = demoDateObject ? Utilities.formatDate(new Date(demoDateObject), timezone, \"yyyy-MM-dd\") : \"\";\n",
    "  const demoDateFU = demoDateObjectFU ? Utilities.formatDate(new Date(demoDateObjectFU), timezone, \"yyyy-MM-dd\") : \"\";\n",
    "\n",
    "\n",
    "  let proposedProductsParam = \"\";\n",
    "  if (proposedProductsRaw) {\n",
    "    const products = String(proposedProductsRaw).trim().split(',').map(p => p.trim()).filter(p => p);\n",
    "    products.forEach(product => {\n",
    "      proposedProductsParam += `&${entry.proposedProducts}=${encodeURIComponent(product)}`;\n",
    "    });\n",
    "  }\n",
    "\n",
    "\n",
    "  // === Build prefilled URL for FORM 2 (Admin Form) ===\n",
    "  let url = `${form2BaseURL}?usp=pp_url`;\n",
    "  url += `&${entry.dealType}=${encodeURIComponent(dealType || \"\")}`;\n",
    "\n",
    "\n",
    "  if (dealType === \"New Deal\") {\n",
    "    url += `&${entry.ownLead}=${encodeURIComponent(ownLeadValue)}`;\n",
    "\n",
    "\n",
    "    if (ownLeadValue === \"Yes\") {\n",
    "      url += `&${entry.clientName}=${encodeURIComponent(clientName || \"\")}`;\n",
    "      url += `&${entry.clientContact}=${encodeURIComponent(clientContact || \"\")}`;\n",
    "    }\n",
    "\n",
    "\n",
    "    url += `&${entry.leadHandledBy}=${encodeURIComponent(leadHandledBy || \"\")}`;\n",
    "    url += `&${entry.demoDate}=${encodeURIComponent(demoDate)}`;\n",
    "    url += `&${entry.companyName}=${encodeURIComponent(companyName || \"\")}`;\n",
    "    url += `&${entry.contactId}=${encodeURIComponent(contactId || \"\")}`;\n",
    "    url += `&${entry.businessDescription}=${encodeURIComponent(businessDescription || \"\")}`;\n",
    "    url += proposedProductsParam;\n",
    "    url += `&${entry.amount}=${encodeURIComponent(amount || \"\")}`;\n",
    "    url += `&${entry.pipeline}=${encodeURIComponent(String(pipeline || \"\").trim())}`;\n",
    "    url += `&${entry.stage}=${encodeURIComponent(String(stage || \"\").trim())}`;\n",
    "    url += `&${entry.status}=${encodeURIComponent(statusNextStep || \"\")}`;\n",
    "    url += `&${entry.notes}=${encodeURIComponent(extraNotes || \"\")}`;\n",
    "\n",
    "\n",
    "  } else if (dealType === \"Follow Up\") {\n",
    "    url += `&${entry.leadHandledByFU}=${encodeURIComponent(leadHandledByFU || \"\")}`;\n",
    "    url += `&${entry.companyNameFU}=${encodeURIComponent(companyNameFU || \"\")}`;\n",
    "    url += `&${entry.dealNameFU}=${encodeURIComponent(dealNameFU || \"\")}`;\n",
    "    url += `&${entry.dealIdFU}=${encodeURIComponent(dealIdFU || \"\")}`;\n",
    "    url += `&${entry.demoDateFU}=${encodeURIComponent(demoDateFU)}`;\n",
    "    url += `&${entry.pipelineFU}=${encodeURIComponent(String(pipelineFU || \"\").trim())}`;\n",
    "    url += `&${entry.stageFU}=${encodeURIComponent(String(stageFU || \"\").trim())}`;\n",
    "    url += `&${entry.status}=${encodeURIComponent(statusNextStep || \"Pending Admin Review\")}`;\n",
    "    url += `&${entry.notes}=${encodeURIComponent(extraNotes || \"\")}`;\n",
    "  }\n",
    "\n",
    "\n",
    "  Logger.log(`Generated Admin Form URL: ${url}`);\n",
    "\n",
    "\n",
    "  // === Email notification ===\n",
    "  const recipient = \"kalaivani.sulwarajan@epos.com.sg\";\n",
    "  const currentCompanyName = dealType === \"New Deal\" ? companyName : companyNameFU;\n",
    "  const currentLeadHandler = dealType === \"New Deal\" ? leadHandledBy : leadHandledByFU;\n",
    "  const subject = `${dealType} Submitted - ${currentCompanyName || \"Unknown Company\"}`;\n",
    " \n",
    "  let body = `Hello Sales Admin,\\n\\nA ${dealType} has been submitted and requires your attention.\\n\\n`;\n",
    "  body += `Lead Handled By: ${currentLeadHandler || \"N/A\"}\\n`;\n",
    "  body += `Company: ${currentCompanyName || \"N/A\"}\\n`;\n",
    "  body += `\\nPlease complete the Sales Admin form here:\\n${url}\\n\\n`;\n",
    "  body += `Best regards,\\nEPOS Automation`;\n",
    "\n",
    "\n",
    "  MailApp.sendEmail(recipient, subject, body);\n",
    "  Logger.log(`Email sent to ${recipient}`);\n",
    "}\n",
    "\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "5669964e",
   "metadata": {},
   "outputs": [],
   "source": [
    "/**** CONFIG ****/\n",
    "const SHEET_NAME = 'SM Form Responses 1';\n",
    "const REMIND_EVERY_DAYS = 7;         // weekly cadence\n",
    "const MAX_AGE_DAYS = 30;             // stop nudging after 30 days from Timestamp\n",
    "\n",
    "// If any of these appear in Status or Stage (incl. Stage - Follow Up), reminders stop:\n",
    "const STOP_STATUSES = [\n",
    "  'payment collected','paid','closed','won','completed','converted',\n",
    "  'drop','dropped','lost','no go'\n",
    "];\n",
    "\n",
    "// Test routing: set true to send all emails to yourself\n",
    "const TEST_MODE = true;\n",
    "const TEST_TO   = 'kalaivani.sulwarajan@epos.com.sg';\n",
    "\n",
    "// Fixed “Update here” link\n",
    "const UPDATE_URL = 'https://forms.gle/pJUEP6DFrgfigtjX9';\n",
    "\n",
    "/**** MAIN ****/\n",
    "function sendWeeklyFollowUpReminders() {\n",
    "  const ss = SpreadsheetApp.getActiveSpreadsheet();\n",
    "  const sh = ss.getSheetByName(SHEET_NAME);\n",
    "  if (!sh) throw new Error(`Sheet \"${SHEET_NAME}\" not found.`);\n",
    "\n",
    "  const headers = sh.getRange(1,1,1,sh.getLastColumn()).getValues()[0].map(h => String(h).trim());\n",
    "  const col = idx(headers);\n",
    "\n",
    "  // Ensure \"Last Reminder Sent\" column exists\n",
    "  let lastSentCol = col.lastReminderSent;\n",
    "  if (!lastSentCol) {\n",
    "    lastSentCol = sh.getLastColumn() + 1;\n",
    "    sh.getRange(1, lastSentCol).setValue('Last Reminder Sent');\n",
    "  }\n",
    "\n",
    "  const lastRow = sh.getLastRow();\n",
    "  if (lastRow <= 1) return;\n",
    "\n",
    "  const rng = sh.getRange(2, 1, lastRow - 1, lastSentCol);\n",
    "  const data = rng.getValues();\n",
    "\n",
    "  const today = toMidnight(new Date());\n",
    "  const perEmail = {};\n",
    "  const writeBack = [];\n",
    "\n",
    "  for (let r = 0; r < data.length; r++) {\n",
    "    const row = data[r];\n",
    "\n",
    "    const ts          = asDate(row[col.timestamp-1]);\n",
    "    const dealType    = str(row[col.dealType-1]);\n",
    "    const email       = str(row[col.email-1]);\n",
    "    const dealOwner   = str(row[(col.dealOwnerFU || col.dealOwner)-1]);\n",
    "    const dealName    = str(row[(col.dealNameFU  || col.dealName)-1]);\n",
    "    const status      = str(row[col.statusNext-1]);\n",
    "    const stageFU     = str(row[col.stageFU-1]);\n",
    "    const pipelineFU  = str(row[col.pipelineFU-1]);\n",
    "    const lastSent    = asDate(row[lastSentCol-1]);\n",
    "\n",
    "    let stamp = row[lastSentCol-1];\n",
    "\n",
    "    // Only process valid timestamp + Follow Up + email present\n",
    "    if (!ts || dealType.toLowerCase() !== 'follow up' || !email) {\n",
    "      if (dealType && dealType.toLowerCase() !== 'follow up' && stamp) stamp = '';\n",
    "      writeBack.push([stamp]);\n",
    "      continue;\n",
    "    }\n",
    "\n",
    "    // Age window\n",
    "    const ageDays = daysBetween(ts, today);\n",
    "    if (ageDays > MAX_AGE_DAYS) { stamp = ''; writeBack.push([stamp]); continue; }\n",
    "\n",
    "    // Stop if status/stage indicate closure/paid/drop/etc.\n",
    "    const stopper = (status + ' ' + stageFU).toLowerCase();\n",
    "    if (STOP_STATUSES.some(s => stopper.includes(s))) { stamp = ''; writeBack.push([stamp]); continue; }\n",
    "\n",
    "    // Optional: pipeline closed\n",
    "    if (pipelineFU && /closed|won|completed|success/i.test(pipelineFU)) {\n",
    "      stamp = ''; writeBack.push([stamp]); continue;\n",
    "    }\n",
    "\n",
    "    // Weekly cadence\n",
    "    const shouldSend = !lastSent || daysBetween(lastSent, today) >= REMIND_EVERY_DAYS;\n",
    "    if (shouldSend) {\n",
    "      if (!perEmail[email]) perEmail[email] = { name: dealOwner || 'there', deals: [] };\n",
    "      perEmail[email].deals.push({\n",
    "        name: dealName || '(Unnamed Deal)',\n",
    "        submitted: ts,\n",
    "        status: status || '—',\n",
    "        stage: stageFU || '—'\n",
    "      });\n",
    "      stamp = today;\n",
    "    }\n",
    "\n",
    "    writeBack.push([stamp]);\n",
    "  }\n",
    "\n",
    "  // Send one email per manager\n",
    "  Object.keys(perEmail).forEach(email => {\n",
    "    const { name, deals } = perEmail[email];\n",
    "    if (!deals.length) return;\n",
    "\n",
    "    const rows = deals.map(d => `\n",
    "      <tr>\n",
    "        <td>${esc(d.name)}</td>\n",
    "        <td>${fmt(d.submitted)}</td>\n",
    "        <td>${esc(d.stage)}</td>\n",
    "        <td>${esc(d.status)}</td>\n",
    "      </tr>`).join('');\n",
    "\n",
    "    const html = `\n",
    "      <div style=\"font-family:Arial,sans-serif;color:#333;\">\n",
    "        <p>Hi ${esc(name)},</p>\n",
    "        <p>This is your weekly reminder to <b>update the stage/pipeline</b> for your open <b>Follow Up</b> deals.\n",
    "           Reminders stop automatically when the stage is updated (e.g., “Payment Collected”) or after 30 days.</p>\n",
    "        <table border=\"1\" cellpadding=\"6\" cellspacing=\"0\" style=\"border-collapse:collapse;margin:12px 0;\">\n",
    "          <tr style=\"background:#f2f2f2;\">\n",
    "            <th>Deal Name</th><th>Submitted</th><th>Stage (FU)</th><th>Status / Next Step</th>\n",
    "          </tr>${rows}\n",
    "        </table>\n",
    "        <p>Update here:<br><a href=\"${UPDATE_URL}\" target=\"_blank\">${UPDATE_URL}</a></p>\n",
    "        <p>— EPOS Automation</p>\n",
    "      </div>`;\n",
    "\n",
    "    if (TEST_MODE) {\n",
    "      MailApp.sendEmail({\n",
    "        to: TEST_TO,\n",
    "        subject: `[TEST] Reminder originally for ${email}`,\n",
    "        htmlBody: `<p><i>This test email was rerouted to you. Original recipient: ${email}</i></p>${html}`\n",
    "      });\n",
    "      Logger.log(`Test email rerouted to ${TEST_TO} (originally ${email})`);\n",
    "    } else {\n",
    "      MailApp.sendEmail({\n",
    "        to: email,\n",
    "        subject: 'Reminder: Update your Follow-Up deals',\n",
    "        htmlBody: html\n",
    "      });\n",
    "      Logger.log(`Live email sent to ${email}`);\n",
    "    }\n",
    "  });\n",
    "\n",
    "  // Persist stamps\n",
    "  sh.getRange(2, lastSentCol, writeBack.length, 1).setValues(writeBack);\n",
    "}\n",
    "\n",
    "/**** HELPERS ****/\n",
    "function idx(h) {\n",
    "  const map = name => h.indexOf(name) + 1 || 0;\n",
    "  return {\n",
    "    timestamp:          map('Timestamp'),\n",
    "    email:              map('Email Address'),\n",
    "    dealType:           map('Is this a New Deal or Follow-Up?'),\n",
    "    dealOwner:          map('Deal Owner'),\n",
    "    dealOwnerFU:        map('Deal Owner - Follow Up'),\n",
    "    demoDate:           map('Demo Date'),\n",
    "    demoDateFU:         map('Demo Date - Follow Up'),\n",
    "    dealName:           map('Deal Name'),\n",
    "    dealNameFU:         map('Deal Name - Follow Up'),\n",
    "    stage:              map('Stage'),\n",
    "    pipeline:           map('Pipeline'),\n",
    "    stageFU:            map('Stage - Follow Up'),\n",
    "    pipelineFU:         map('Pipeline - Follow Up'),\n",
    "    statusNext:         map('Status / Next Step'),\n",
    "    lastReminderSent:   map('Last Reminder Sent')\n",
    "  };\n",
    "}\n",
    "\n",
    "function str(v)      { return (v === null || v === undefined) ? '' : String(v).trim(); }\n",
    "function toMidnight(d){ const t = new Date(d); t.setHours(0,0,0,0); return t; }\n",
    "function daysBetween(d1,d2){ return Math.floor((toMidnight(d2)-toMidnight(d1))/(24*60*60*1000)); }\n",
    "function asDate(v)   { return v instanceof Date && !isNaN(v) ? v : null; }\n",
    "// dd/MM/yyyy\n",
    "function fmt(d)      { return Utilities.formatDate(d, Session.getScriptTimeZone(), 'dd/MM/yyyy'); }\n",
    "function esc(s)      { return String(s).replace(/[&<>\"']/g, m => ({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',\"'\":'&#39;'})[m]); }\n",
    "\n",
    "/**** TRIGGERS ****/\n",
    "function installDailyTrigger() {\n",
    "  ScriptApp.newTrigger('sendWeeklyFollowUpReminders').timeBased().atHour(9).everyDays(1).create();\n",
    "}\n",
    "function installWeeklyTrigger() {\n",
    "  ScriptApp.newTrigger('sendWeeklyFollowUpReminders').timeBased().onWeekDay(ScriptApp.WeekDay.MONDAY).atHour(9).create();\n",
    "}\n",
    "\n",
    "\n"
   ]
  }
 ],
 "metadata": {
  "language_info": {
   "name": "python"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
